# Generated by Django 3.1.7 on 2021-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='content_type',
        ),
    ]
