# Generated by Django 3.1.7 on 2021-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_remove_picture_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
    ]
