# Generated by Django 3.1.7 on 2021-03-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20210310_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
