# Generated by Django 3.1.7 on 2021-03-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20210310_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
