# Generated by Django 3.1.7 on 2021-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_auto_20210311_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
    ]
