# Generated by Django 3.1.7 on 2021-03-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_auto_20210311_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_url',
        ),
    ]
