# Generated by Django 3.1.7 on 2021-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_auto_20210311_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
